### ISSUE TITLE
Ensure query path is completely parallelised

### ISSUE THREAD

**Issue by jml** [weaveworks/frankenstein#8]
*From @tomwilkie*

*Copied from original issue: tomwilkie/frankenstein#7*

**Comment by jml** [comment]
*From @tomwilkie*

This limits scalability.

**Comment by jml** [comment]
*From @jml*

Which RPCs need to be parallelised? This one? https://github.com/tomwilkie/frankenstein/blob/master/distributor.go#L228

**Comment by jml** [comment]
*From @tomwilkie*

I was thinking this, but it looks like you beat me to it: https://github.com/tomwilkie/frankenstein/blob/master/distributor.go#L157

That one isn't particularly performance sensitive. Will need to check query path is completely parallelised.

**Comment by jml** [comment]
Bits that I can find that aren't:

- [ ] `MergeQuerier` goes through each sub-querier [one at a time](https://github.com/weaveworks/frankenstein/blob/master/querier.go#L110) (although sub-queriers themselves are parallel)
- [ ] Likewise `MergeQuerier.LabelValuesForLabelName`
- [ ] After fetching from chunk store in parallel, we [fingerprint in serial](https://github.com/weaveworks/frankenstein/blob/master/querier.go#L51) (I don't think this is a big deal)
- [ ] `Distributor.LabelValuesForLabelName` ([code](https://github.com/weaveworks/frankenstein/blob/master/distributor.go#L228)). Mentioned above.

Cache backfill is also done in parallel.

**Comment by jml** [comment]
@tomwilkie Any of these matter?

**Comment by juliusv** [comment]
I think neither of these are a huge deal at the moment, since querying the ingesters is so fast. Still, for the `LabelValuesForLabelName` that has to query every ingester, it might make sense at some point. I'm more worried about the reliability aspect there than the efficiency (`LabelValuesForLabelName` fails if even only a single ingester is down).

I expect that fingerprinting speed will never be an issue, it's just too fast.

**Comment by jml** [comment]
Thanks @juliusv. I'm going to call this done then. @tomwilkie can re-open if necessary.
